# Generated by Django 4.2.7 on 2025-09-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_code",
                    models.CharField(
                        choices=[
                            ("demirbank", "Демирбанк"),
                            ("odengi", "О! Деньги"),
                            ("bakai", "Бакай"),
                            ("balance", "Balance.kg"),
                            ("megapay", "MegaPay"),
                            ("mbank", "MBank"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Код банка",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(max_length=100, verbose_name="Название банка"),
                ),
                (
                    "is_enabled_deposit",
                    models.BooleanField(
                        default=True, verbose_name="Включен для пополнения"
                    ),
                ),
                (
                    "is_enabled_withdraw",
                    models.BooleanField(
                        default=True, verbose_name="Включен для вывода"
                    ),
                ),
                (
                    "url_template",
                    models.CharField(max_length=200, verbose_name="Шаблон URL"),
                ),
                (
                    "icon",
                    models.CharField(
                        default="🏦", max_length=10, verbose_name="Иконка"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Настройки банка",
                "verbose_name_plural": "Настройки банков",
                "ordering": ["bank_name"],
            },
        ),
        migrations.CreateModel(
            name="BotSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Бот активен"),
                ),
                (
                    "maintenance_message",
                    models.TextField(
                        default="🔧 Технические работы\nБот временно недоступен. Попробуйте позже.",
                        verbose_name="Сообщение о технических работах",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Настройки бота",
                "verbose_name_plural": "Настройки бота",
            },
        ),
        migrations.CreateModel(
            name="BroadcastMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("message", models.TextField(verbose_name="Текст сообщения")),
                (
                    "is_sent",
                    models.BooleanField(default=False, verbose_name="Отправлено"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время отправки"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Сообщение для рассылки",
                "verbose_name_plural": "Сообщения для рассылки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QRHash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_code",
                    models.CharField(
                        choices=[
                            ("demirbank", "Демирбанк"),
                            ("odengi", "О! Деньги"),
                            ("bakai", "Бакай"),
                            ("balance", "Balance.kg"),
                            ("megapay", "MegaPay"),
                            ("mbank", "MBank"),
                        ],
                        max_length=20,
                        verbose_name="Банк",
                    ),
                ),
                (
                    "hash_value",
                    models.CharField(max_length=100, verbose_name="QR Hash"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "QR Hash",
                "verbose_name_plural": "QR Hash",
                "ordering": ["bank_code", "-created_at"],
                "unique_together": {("bank_code", "hash_value")},
            },
        ),
    ]
