# Generated by Django 4.2.7 on 2025-09-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_control", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="Ключ"),
                ),
                ("value", models.TextField(verbose_name="Значение")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Описание"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Конфигурация бота",
                "verbose_name_plural": "Конфигурации бота",
                "ordering": ["key"],
            },
        ),
    ]
