# Generated by Django 4.2.7 on 2025-09-11 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bot_control", "0002_botconfiguration"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank",
                    models.CharField(
                        choices=[
                            ("optima", "OptimaBank"),
                            ("demirbank", "Демирбанк"),
                            ("odengi", "О! Деньги"),
                            ("bakai", "Бакай"),
                            ("balance", "Balance.kg"),
                            ("megapay", "MegaPay"),
                            ("mbank", "MBank"),
                        ],
                        max_length=20,
                        verbose_name="Банк",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="KGS", max_length=3, verbose_name="Валюта"
                    ),
                ),
                (
                    "notification_text",
                    models.TextField(verbose_name="Текст уведомления"),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Сырые данные"
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="Обработано"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время обработки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время получения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление банка",
                "verbose_name_plural": "Уведомления банков",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DepositRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank",
                    models.CharField(
                        choices=[
                            ("optima", "OptimaBank"),
                            ("demirbank", "Демирбанк"),
                            ("odengi", "О! Деньги"),
                            ("bakai", "Бакай"),
                            ("balance", "Balance.kg"),
                            ("megapay", "MegaPay"),
                            ("mbank", "MBank"),
                        ],
                        max_length=20,
                        verbose_name="Банк",
                    ),
                ),
                (
                    "amount_min",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Минимальная сумма",
                    ),
                ),
                (
                    "amount_max",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Максимальная сумма",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "auto_approve",
                    models.BooleanField(default=False, verbose_name="Автоодобрение"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Правило пополнения",
                "verbose_name_plural": "Правила пополнения",
                "ordering": ["bank", "amount_min"],
            },
        ),
        migrations.CreateModel(
            name="PlayerBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(verbose_name="ID пользователя")),
                ("bookmaker", models.CharField(max_length=20, verbose_name="Букмекер")),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Баланс",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее обновление"
                    ),
                ),
            ],
            options={
                "verbose_name": "Баланс игрока",
                "verbose_name_plural": "Балансы игроков",
                "ordering": ["-last_updated"],
                "unique_together": {("user_id", "bookmaker")},
            },
        ),
        migrations.CreateModel(
            name="AutoDepositRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(verbose_name="ID пользователя")),
                ("bookmaker", models.CharField(max_length=20, verbose_name="Букмекер")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("processing", "Обрабатывается"),
                            ("completed", "Завершено"),
                            ("failed", "Ошибка"),
                            ("cancelled", "Отменено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Сообщение об ошибке"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время обработки"
                    ),
                ),
                (
                    "bank_notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot_control.banknotification",
                        verbose_name="Уведомление банка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка автопополнения",
                "verbose_name_plural": "Заявки автопополнения",
                "ordering": ["-created_at"],
            },
        ),
    ]
