# Generated by Django 4.2.7 on 2025-09-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_control", "0003_banknotification_depositrule_playerbalance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepositRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(verbose_name="ID пользователя")),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Username"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Банк"),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID транзакции"
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[("deposit", "Пополнение"), ("withdraw", "Вывод")],
                        default="deposit",
                        max_length=20,
                        verbose_name="Тип заявки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("completed", "Завершена"),
                            ("auto_completed", "Автопополнена"),
                            ("rejected", "Отклонена"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("photo_url", models.URLField(blank=True, verbose_name="Фото чека")),
                (
                    "admin_comment",
                    models.TextField(blank=True, verbose_name="Комментарий админа"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершена"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "ordering": ["-created_at"],
            },
        ),
    ]
