# Generated by Django 4.2.7 on 2025-09-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_control", "0004_depositrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="depositrequest",
            name="bookmaker",
            field=models.CharField(blank=True, max_length=50, verbose_name="Букмекер"),
        ),
    ]
