# Generated by Django 4.2.7 on 2025-09-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_control", "0005_depositrequest_bookmaker"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название аккаунта"),
                ),
                (
                    "bank_type",
                    models.CharField(
                        choices=[
                            ("demirbank", "Демирбанк"),
                            ("optima", "OptimaBank"),
                            ("odengi", "О! Деньги"),
                            ("bakai", "Бакай"),
                            ("balance", "Balance.kg"),
                            ("megapay", "MegaPay"),
                            ("mbank", "MBank"),
                        ],
                        max_length=20,
                        verbose_name="Тип банка",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Email для уведомлений"
                    ),
                ),
                (
                    "email_password",
                    models.CharField(
                        help_text="Или App Password для Gmail",
                        max_length=255,
                        verbose_name="Пароль email",
                    ),
                ),
                ("qr_hash", models.TextField(verbose_name="QR хеш для этого аккаунта")),
                (
                    "sender_pattern",
                    models.CharField(
                        default="info@",
                        max_length=200,
                        verbose_name="Паттерн отправителя",
                    ),
                ),
                (
                    "amount_pattern",
                    models.CharField(
                        default="на сумму\\s+([\\d,]+\\.?\\d*)\\s+KGS",
                        max_length=200,
                        verbose_name="Паттерн суммы",
                    ),
                ),
                (
                    "date_pattern",
                    models.CharField(
                        default="от\\s+(\\d{2}\\.\\d{2}\\.\\d{4})\\s+(\\d{2}:\\d{2}:\\d{2})",
                        max_length=200,
                        verbose_name="Паттерн даты",
                    ),
                ),
                (
                    "gmail_credentials_file",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Файл credentials.json",
                    ),
                ),
                (
                    "gmail_token_file",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Файл token.json",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
            ],
            options={
                "verbose_name": "Банковский аккаунт",
                "verbose_name_plural": "Банковские аккаунты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="qrhash",
            name="amount_pattern",
            field=models.CharField(
                default="на сумму\\s+([\\d,]+\\.?\\d*)\\s+KGS",
                max_length=200,
                verbose_name="Паттерн суммы",
            ),
        ),
        migrations.AddField(
            model_name="qrhash",
            name="date_pattern",
            field=models.CharField(
                default="от\\s+(\\d{2}\\.\\d{2}\\.\\d{4})\\s+(\\d{2}:\\d{2}:\\d{2})",
                max_length=200,
                verbose_name="Паттерн даты",
            ),
        ),
        migrations.AddField(
            model_name="qrhash",
            name="gmail_email",
            field=models.EmailField(
                default="",
                help_text="Ваша почта, куда приходят уведомления",
                max_length=254,
                verbose_name="Gmail для мониторинга",
            ),
        ),
        migrations.AddField(
            model_name="qrhash",
            name="gmail_password",
            field=models.CharField(
                default="",
                help_text="Пароль от Gmail или App Password",
                max_length=255,
                verbose_name="Пароль Gmail",
            ),
        ),
        migrations.AddField(
            model_name="qrhash",
            name="sender_email",
            field=models.EmailField(
                default="info@demirbank.kg",
                help_text="От кого приходят уведомления (например: info@demirbank.kg)",
                max_length=254,
                verbose_name="Email отправителя",
            ),
        ),
        migrations.AlterField(
            model_name="qrhash",
            name="hash_value",
            field=models.TextField(verbose_name="QR Hash"),
        ),
    ]
