# Generated by Django 4.2.7 on 2025-09-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_control", "0006_bankaccount_qrhash_amount_pattern_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qrhash",
            options={
                "ordering": ["-is_main", "-created_at"],
                "verbose_name": "Аккаунт Демирбанка",
                "verbose_name_plural": "Аккаунты Демирбанка",
            },
        ),
        migrations.AlterUniqueTogether(
            name="qrhash",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="qrhash",
            name="account_name",
            field=models.CharField(
                default="Демирбанк Аккаунт",
                help_text="Например: Демирбанк Аккаунт 1",
                max_length=100,
                verbose_name="Название аккаунта",
            ),
        ),
        migrations.AddField(
            model_name="qrhash",
            name="is_main",
            field=models.BooleanField(
                default=False,
                help_text="Используется для пополнений по умолчанию",
                verbose_name="Основной аккаунт",
            ),
        ),
        migrations.RemoveField(
            model_name="qrhash",
            name="bank_code",
        ),
        migrations.RemoveField(
            model_name="qrhash",
            name="sender_email",
        ),
    ]
