# Generated by Django 4.2.7 on 2025-09-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bot_control",
            "0007_alter_qrhash_options_alter_qrhash_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BotDepositRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(verbose_name="ID пользователя")),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Username"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Фамилия"
                    ),
                ),
                (
                    "bookmaker",
                    models.CharField(
                        choices=[
                            ("1xbet", "1XBET"),
                            ("1win", "1WIN"),
                            ("melbet", "MELBET"),
                            ("mostbet", "MOSTBET"),
                        ],
                        max_length=20,
                        verbose_name="Букмекер",
                    ),
                ),
                (
                    "account_id",
                    models.CharField(max_length=50, verbose_name="ID аккаунта"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                ("bank", models.CharField(max_length=50, verbose_name="Банк")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("processing", "Обрабатывается"),
                            ("completed", "Завершено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "receipt_photo",
                    models.TextField(blank=True, verbose_name="Фото чека (file_id)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Обработано"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на пополнение",
                "verbose_name_plural": "Заявки на пополнение",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BotWithdrawRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(verbose_name="ID пользователя")),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Username"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Фамилия"
                    ),
                ),
                (
                    "bookmaker",
                    models.CharField(
                        choices=[
                            ("1xbet", "1XBET"),
                            ("1win", "1WIN"),
                            ("melbet", "MELBET"),
                            ("mostbet", "MOSTBET"),
                        ],
                        max_length=20,
                        verbose_name="Букмекер",
                    ),
                ),
                (
                    "account_id",
                    models.CharField(max_length=50, verbose_name="ID аккаунта"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                ("bank", models.CharField(max_length=50, verbose_name="Банк")),
                (
                    "withdrawal_code",
                    models.CharField(max_length=100, verbose_name="Код вывода"),
                ),
                (
                    "qr_photo",
                    models.TextField(blank=True, verbose_name="QR код (file_id)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("processing", "Обрабатывается"),
                            ("completed", "Завершено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Обработано"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на вывод",
                "verbose_name_plural": "Заявки на вывод",
                "ordering": ["-created_at"],
            },
        ),
    ]
