# Generated by Django 4.2.7 on 2025-09-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_control", "0008_botdepositrequest_botwithdrawrequest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DepositRequest",
        ),
        migrations.AlterModelOptions(
            name="autodepositrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
        migrations.RemoveField(
            model_name="autodepositrequest",
            name="bank_notification",
        ),
        migrations.RemoveField(
            model_name="autodepositrequest",
            name="error_message",
        ),
        migrations.RemoveField(
            model_name="autodepositrequest",
            name="processed_at",
        ),
        migrations.AddField(
            model_name="autodepositrequest",
            name="admin_comment",
            field=models.TextField(blank=True, verbose_name="Комментарий админа"),
        ),
        migrations.AddField(
            model_name="autodepositrequest",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Банк"),
        ),
        migrations.AddField(
            model_name="autodepositrequest",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Завершена"),
        ),
        migrations.AddField(
            model_name="autodepositrequest",
            name="photo_url",
            field=models.URLField(blank=True, verbose_name="Фото чека"),
        ),
        migrations.AddField(
            model_name="autodepositrequest",
            name="request_type",
            field=models.CharField(
                choices=[("deposit", "Пополнение"), ("withdraw", "Вывод")],
                default="deposit",
                max_length=20,
                verbose_name="Тип заявки",
            ),
        ),
        migrations.AddField(
            model_name="autodepositrequest",
            name="transaction_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ID транзакции"
            ),
        ),
        migrations.AddField(
            model_name="autodepositrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
        ),
        migrations.AddField(
            model_name="autodepositrequest",
            name="username",
            field=models.CharField(blank=True, max_length=100, verbose_name="Username"),
        ),
        migrations.AlterField(
            model_name="autodepositrequest",
            name="bookmaker",
            field=models.CharField(blank=True, max_length=50, verbose_name="Букмекер"),
        ),
        migrations.AlterField(
            model_name="autodepositrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
        ),
        migrations.AlterField(
            model_name="autodepositrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает"),
                    ("completed", "Завершена"),
                    ("auto_completed", "Автопополнена"),
                    ("rejected", "Отклонена"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
