# Generated by Django 4.2.7 on 2025-09-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_control", "0009_delete_depositrequest_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotDepositRequestRaw",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField(verbose_name="ID пользователя")),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Username"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=255, verbose_name="Имя"),
                ),
                ("bookmaker", models.CharField(max_length=50, verbose_name="Букмекер")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                (
                    "account_id",
                    models.CharField(max_length=255, verbose_name="ID счета"),
                ),
                (
                    "photo_file_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Фото чека"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending", max_length=50, verbose_name="Статус"
                    ),
                ),
                ("created_at", models.DateTimeField(verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "Заявка на пополнение (из бота)",
                "verbose_name_plural": "Заявки на пополнение (из бота)",
                "db_table": "deposit_requests",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BotTransaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField(verbose_name="ID пользователя")),
                ("bookmaker", models.CharField(max_length=50, verbose_name="Букмекер")),
                ("trans_type", models.CharField(max_length=50, verbose_name="Тип")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                ("status", models.CharField(max_length=50, verbose_name="Статус")),
                (
                    "photo_file_id",
                    models.CharField(blank=True, max_length=255, verbose_name="Фото"),
                ),
                ("created_at", models.DateTimeField(verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "Транзакция (из бота)",
                "verbose_name_plural": "Транзакции (из бота)",
                "db_table": "transactions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BotUser",
            fields=[
                (
                    "user_id",
                    models.BigIntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID пользователя",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Username"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=255, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Фамилия"
                    ),
                ),
                (
                    "language",
                    models.CharField(default="ru", max_length=10, verbose_name="Язык"),
                ),
                ("created_at", models.DateTimeField(verbose_name="Дата регистрации")),
            ],
            options={
                "verbose_name": "Пользователь бота",
                "verbose_name_plural": "Пользователи бота",
                "db_table": "users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BotWithdrawRequestRaw",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField(verbose_name="ID пользователя")),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Username"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=255, verbose_name="Имя"),
                ),
                ("bookmaker", models.CharField(max_length=50, verbose_name="Букмекер")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                (
                    "account_id",
                    models.CharField(max_length=255, verbose_name="ID счета"),
                ),
                (
                    "withdrawal_code",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Код вывода"
                    ),
                ),
                (
                    "qr_photo",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="QR фото"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending", max_length=50, verbose_name="Статус"
                    ),
                ),
                ("created_at", models.DateTimeField(verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "Заявка на вывод (из бота)",
                "verbose_name_plural": "Заявки на вывод (из бота)",
                "db_table": "withdrawals",
                "managed": False,
            },
        ),
    ]
