# Generated by Django 5.2.6 on 2025-09-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_control", "0010_botdepositrequestraw_bottransaction_botuser_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotKVSetting",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Ключ",
                    ),
                ),
                ("value", models.TextField(blank=True, verbose_name="Значение")),
                (
                    "created_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Обновлено"
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка бота (KV)",
                "verbose_name_plural": "Настройки бота (KV)",
                "db_table": "bot_settings",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="botdepositrequest",
            name="receipt_photo_url",
            field=models.URLField(blank=True, default="", verbose_name="URL фото чека"),
        ),
        migrations.AddField(
            model_name="botwithdrawrequest",
            name="qr_photo_url",
            field=models.URLField(blank=True, default="", verbose_name="URL QR/чека"),
        ),
        migrations.AlterField(
            model_name="botwithdrawrequest",
            name="qr_photo",
            field=models.TextField(blank=True, verbose_name="QR/чек (file_id)"),
        ),
    ]
