# Generated by Django 4.2.7 on 2025-09-27 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "bot_control",
            "0011_botkvsetting_botdepositrequest_receipt_photo_url_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoUnifiedRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(verbose_name="ID пользователя")),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Username"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Банк"),
                ),
                (
                    "bookmaker",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Букмекер"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID транзакции"
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[("deposit", "Пополнение"), ("withdraw", "Вывод")],
                        default="deposit",
                        max_length=20,
                        verbose_name="Тип заявки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("completed", "Завершена"),
                            ("auto_completed", "Автопополнена"),
                            ("rejected", "Отклонена"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("photo_url", models.URLField(blank=True, verbose_name="Фото чека")),
                (
                    "admin_comment",
                    models.TextField(blank=True, verbose_name="Комментарий админа"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершена"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка (унифицированная)",
                "verbose_name_plural": "Заявки (унифицированные)",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ReferralWithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(verbose_name="ID пользователя")),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Username"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Фамилия"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма вывода"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="KGS", max_length=10, verbose_name="Валюта"
                    ),
                ),
                (
                    "bookmaker",
                    models.CharField(
                        choices=[
                            ("1xbet", "1XBET"),
                            ("1win", "1WIN"),
                            ("melbet", "MELBET"),
                            ("mostbet", "MOSTBET"),
                        ],
                        max_length=20,
                        verbose_name="Букмекер",
                    ),
                ),
                (
                    "bookmaker_account_id",
                    models.CharField(max_length=64, verbose_name="ID аккаунта в БК"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_card", "Банковская карта"),
                            ("e_wallet", "Электронный кошелек"),
                            ("crypto", "Криптовалюта"),
                        ],
                        max_length=20,
                        verbose_name="Способ выплаты",
                    ),
                ),
                (
                    "wallet_details",
                    models.TextField(verbose_name="Реквизиты для выплаты"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает обработки"),
                            ("processing", "В обработке"),
                            ("completed", "Выплачено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус заявки",
                    ),
                ),
                (
                    "admin_comment",
                    models.TextField(
                        blank=True, verbose_name="Комментарий администратора"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата обработки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на вывод реферальных",
                "verbose_name_plural": "Заявки на вывод реферальных",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="autodepositrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Заявка автопополнения",
                "verbose_name_plural": "Заявки автопополнения",
            },
        ),
        migrations.RemoveField(
            model_name="autodepositrequest",
            name="admin_comment",
        ),
        migrations.RemoveField(
            model_name="autodepositrequest",
            name="bank_name",
        ),
        migrations.RemoveField(
            model_name="autodepositrequest",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="autodepositrequest",
            name="photo_url",
        ),
        migrations.RemoveField(
            model_name="autodepositrequest",
            name="request_type",
        ),
        migrations.RemoveField(
            model_name="autodepositrequest",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="autodepositrequest",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="autodepositrequest",
            name="username",
        ),
        migrations.AddField(
            model_name="autodepositrequest",
            name="bank_notification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bot_control.banknotification",
                verbose_name="Уведомление банка",
            ),
        ),
        migrations.AddField(
            model_name="autodepositrequest",
            name="error_message",
            field=models.TextField(
                blank=True, null=True, verbose_name="Сообщение об ошибке"
            ),
        ),
        migrations.AddField(
            model_name="autodepositrequest",
            name="processed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время обработки"
            ),
        ),
        migrations.AlterField(
            model_name="autodepositrequest",
            name="bookmaker",
            field=models.CharField(max_length=20, verbose_name="Букмекер"),
        ),
        migrations.AlterField(
            model_name="autodepositrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время создания"
            ),
        ),
        migrations.AlterField(
            model_name="autodepositrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает"),
                    ("processing", "Обрабатывается"),
                    ("completed", "Завершено"),
                    ("failed", "Ошибка"),
                    ("cancelled", "Отменено"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
