# Generated by Django 4.2.7 on 2025-09-27 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot_control", "0012_autounifiedrequest_referralwithdrawalrequest_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralRequestsBoard",
            fields=[],
            options={
                "verbose_name": "Обработка реферальных заявок",
                "verbose_name_plural": "Обработка реферальных заявок",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("bot_control.referralwithdrawalrequest",),
        ),
    ]
