# Generated by Django 5.2.7 on 2025-10-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_control', '0013_referralrequestsboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botconfiguration',
            options={'verbose_name': 'Настройка бота', 'verbose_name_plural': 'Настройки бота'},
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='key',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='value',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='BankWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(choices=[('mbank', 'MBank'), ('bakai', 'Bakai'), ('optima', 'Optima')], max_length=20, verbose_name='Банк')),
                ('account_name', models.CharField(max_length=100, verbose_name='Название реквизита')),
                ('hash_value', models.TextField(verbose_name='Hash/реквизит')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основной для банка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Кошелёк банка',
                'verbose_name_plural': 'Кошельки банков',
                'ordering': ['bank_code', '-is_main', '-is_active', '-created_at'],
                'indexes': [models.Index(fields=['bank_code', 'is_active'], name='bot_control_bank_co_b7d632_idx'), models.Index(fields=['bank_code', 'is_main'], name='bot_control_bank_co_d7c828_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('raw_message', models.TextField()),
                ('status', models.CharField(choices=[('received', 'Получено'), ('error', 'Ошибка'), ('processed', 'Обработано')], default='received', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Лог платежа',
                'verbose_name_plural': 'Логи платежей',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['timestamp'], name='bot_control_timesta_d2013b_idx'), models.Index(fields=['bank'], name='bot_control_bank_3177e4_idx'), models.Index(fields=['status'], name='bot_control_status_44ad98_idx')],
            },
        ),
    ]
