# Generated by Django 5.2.7 on 2025-10-21 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_control', '0014_alter_botconfiguration_options_and_more'),
    ]

    operations = [
    ]
