# Generated by Django 5.2.7 on 2025-10-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_control', '0016_create_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='banksettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='banksettings',
            name='is_enabled_deposit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='banksettings',
            name='is_enabled_withdraw',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='banksettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]










