# Generated by Django 5.2.7 on 2025-10-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_control', '0017_add_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankwallet',
            name='bank_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]










