# Generated by Django 5.2.7 on 2025-10-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_control', '0018_add_bankwallet_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankwallet',
            name='bank_code',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='bankwallet',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]










