# Generated by Django 5.2.7 on 2025-10-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_control', '0019_add_bankwallet_code_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bookmaker', models.CharField(blank=True, max_length=100, null=True)),
                ('account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('request_type', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('withdrawal_code', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_file_url', models.TextField(blank=True, null=True)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
